### PR TITLE
197 txpower double

### PR DESCRIPTION
**Pull request by fhilg**
## Type of this PR 

- [ ] Bug fix
- [x] Enhancement

## Description

* type of property `power` of `AdHocModuleConfiguration` changed from `int` to `double`
* `ClientServerChannel`'s protocol left unchanged
* this PR is interlocked with OMNeT++ federate, ns-3 federate and an internal repository

## Issue(s) related to this PR

 * internal issue 197
 
 
## Affected parts of the online documentation

Are there any parts in the online documentation which are affected by this PR?

## Definition of Done

- [x] You have read CONTRIBUTING.md carefully.
- [x] You have signed the [Contributor License Agreement](http://www.eclipse.org/legal/CLA.php).
- [ ] All commits are signed-off (`-s`) with your mail address of your Eclipse Account.
- [x] `origin/main` has been merged into your Fork.
- [x] New functionality is covered by unit tests or integration tests. Code coverage must not decrease.
- [x] There are no new SpotBugs warnings. 
- [x] Coding guidelines have been observed (see CONTRIBUTING.md).
- [x] All tests pass.

### CODE REVIEW

**Comment by kschrab** [comment]
I'd have assumed changes in the ClientServerChannel as the power is transmitted to the ns3/OMNeT++ federate. Please check if you missed this.

**Comment by fhilg** [comment]
You are right. This change was intentionally left out. A protocol change involves change of ns-3 federate and OMNeT++ federate, too. I missed to comment this. What about a separation as another issue?

**Comment by kschrab** [comment]
> You are right. This change was intentionally left out. A protocol change involves change of ns-3 federate and OMNeT++ federate, too. I missed to comment this. What about a separation as another issue?

As this change would not help us without changing federates too, I would prefer to do this within this issue.

**Comment by rprotzmann** [comment]
> 
> 
> > You are right. This change was intentionally left out. A protocol change involves change of ns-3 federate and OMNeT++ federate, too. I missed to comment this. What about a separation as another issue?
> 
> As this change would not help us without changing federates too, I would prefer to do this within this issue.

I second Karls opinion.

The change should enable users to configure the `TxPower` in decimal values

1. directly from the ns3-federate-config.xml or the omnetpp.ini (as it is already possible)
2. as well as configure decimal values from the application using the AdhocModuleConfiguration.. and this includes closing the whole chain from Application -> AbstractNetworkAmbassador -> ClientserverChannel -> ns-3 Federate / Omnetpp Federate

**Comment by fhilg** [comment]
I changed the protocol and the federates accordingly. Now, there are 4 repositories involved.

**Review by kschrab — APPROVED** [review]

**Pull request merged**
